// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfNlzfqAOxGOO3BS2tF7-VXtjtxdYja1I',
    appId: '1:705089503001:web:c7dc89fca862df03fc8f88',
    messagingSenderId: '705089503001',
    projectId: 'fitdays-3c0b5',
    authDomain: 'fitdays-3c0b5.firebaseapp.com',
    storageBucket: 'fitdays-3c0b5.firebasestorage.app',
    measurementId: 'G-4KYGYFWQVM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ5RFYFdU7RiV3gkzqaEEYs_ZfxKMRxS4',
    appId: '1:705089503001:android:ad6e3d6909caf59bfc8f88',
    messagingSenderId: '705089503001',
    projectId: 'fitdays-3c0b5',
    storageBucket: 'fitdays-3c0b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAv2uWXEJPnjRg08iOop-MmYOJgvJ7XGLs',
    appId: '1:705089503001:ios:decda0d5ebe34db5fc8f88',
    messagingSenderId: '705089503001',
    projectId: 'fitdays-3c0b5',
    storageBucket: 'fitdays-3c0b5.firebasestorage.app',
    iosBundleId: 'com.fitdays.training',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAv2uWXEJPnjRg08iOop-MmYOJgvJ7XGLs',
    appId: '1:705089503001:ios:c366a425c3c3abeefc8f88',
    messagingSenderId: '705089503001',
    projectId: 'fitdays-3c0b5',
    storageBucket: 'fitdays-3c0b5.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfNlzfqAOxGOO3BS2tF7-VXtjtxdYja1I',
    appId: '1:705089503001:web:38a967d73b8422b2fc8f88',
    messagingSenderId: '705089503001',
    projectId: 'fitdays-3c0b5',
    authDomain: 'fitdays-3c0b5.firebaseapp.com',
    storageBucket: 'fitdays-3c0b5.firebasestorage.app',
    measurementId: 'G-3VFT0GLMTJ',
  );
}